name: Java CI/CD Pipeline - Develop
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: divulgaif-vps
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/divulgaif/back-divulgaif
          
          git checkout develop
          git pull origin develop
          
          cd ../infra-divulgaif
          docker compose -f docker-compose.develop.yml up -d --build backend-dev
          
